apiVersion: v1
kind: ReplicationController
metadata:
  name: bonc-broker
  namespace: default
spec:
  replicas: 1
  selector:
    app: bonc-broker
  template:
    metadata:
      labels:
        app: bonc-broker
    spec:
        nodeName: 172-16-3-30
        containers:
        - name: bonc-broker
          image: 172.16.3.50:5000/bonc-broker:v1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /opt/bonc-broker-log
            name: bonc-broker-log
        volumes:
        - name: bonc-broker-log
          hostPath:
            path: /opt/bonc-broker/log

---

apiVersion: v1
kind: Service
metadata:
  name: bonc-broker
  namespace: default
spec:
  type: NodePort
  ports:
  - name: bonc-broker
    port: 8080
    targetPort: 8080
  selector:
    app: bonc-broker

---

