apiVersion: v1
kind: ReplicationController
metadata:
  name: bonc-broker-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    app: bonc-broker-mysql
  template:
    metadata:
      labels:
        app: bonc-broker-mysql
    spec:
        nodeName: 172-16-3-30
        containers:
        - name: bonc-broker-mysql
          image: 172.16.3.50:5000/mysql:5.7
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: data-mysql
        volumes:
        - name: data-mysql
          hostPath:
            path: /opt/bonc-broker/mysql

---

apiVersion: v1
kind: Service
metadata:
  name: bonc-broker-mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: bonc-broker-mysql
